"""Add support for categories

Revision ID: 46c183d16342
Revises: beda5b2b7764
Create Date: 2018-01-31 17:26:58.103322

"""

# revision identifiers, used by Alembic.
revision = '46c183d16342'
down_revision = 'beda5b2b7764'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], [u'categories.id'], ),
    sa.ForeignKeyConstraint(['team_id'], [u'teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id')
    )
    op.create_table('dashboard_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], [u'categories.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], [u'dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slice_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('slice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], [u'categories.id'], ),
    sa.ForeignKeyConstraint(['slice_id'], [u'slices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slice_category')
    op.drop_table('dashboard_category')
    op.drop_table('categories')
    # ### end Alembic commands ###
